# Compter-Vision
My technology stack in computer vision.

![Alt text](image.png)
## 1. **Local structure matrix**

$A=\sum_{u,v} w(u,v) \begin{pmatrix} I_x^2 & I_xI_y \\ I_xI_y& I_y^2\end{pmatrix} =\begin {pmatrix} <I_x>^2 & <I_xI_y> \\ <I_xI_y> & <I_y^2> \end{pmatrix}$

## 2. **A python function convolve2d**

In [2]:
import numpy as np
import scipy as sp

In [5]:
from scipy.signal import convolve2d
#A = np.array([[1,1,1],[3,3,3],[6,6,6]])
#B = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
#C = convolve2d(A,B,mode='same',boundary='fill',fillvalue=0)
#print(C)
# to get the output as large as A, set mode = 'same'
# to fill the extra elements, set boundary = 'fill'
# to set the value of the extra elements, set fillvalue = <whatever>

#I = np.array([[2,2,5,5,1],[2,5,5,1,1],[5,5,1,1,1],[5,1,1,1,0],[1,1,1,0,0]])
#Gx = np.array([[-1,0,1]])
#Gy = np.array([[-1,0,1]]).reshape(3,1)
#Ix = convolve2d(I,Gx,mode='same',boundary='fill',fillvalue=0)
#Iy = convolve2d(I,Gy,mode='same',boundary='fill',fillvalue=0)
#Ixx = Ix**2
#Iyy = Iy**2
#Ixy = Ix * Iy
#print(Ixy)

A = np.array([[1,1,1],[3,3,3],[6,6,6]])

Sx = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
Sy = np.array([[-1,-2,-1],[0,0,0],[1,2,1]])

Ix = convolve2d(A,Sx,mode='full',boundary='fill',fillvalue=0)
Iy = convolve2d(A,Sy,mode='full',boundary='fill',fillvalue=0)
print(Ix)
print(Iy)

[[ -1  -1   0   1   1]
 [ -5  -5   0   5   5]
 [-13 -13   0  13  13]
 [-15 -15   0  15  15]
 [ -6  -6   0   6   6]]
[[ -1  -3  -4  -3  -1]
 [ -3  -9 -12  -9  -3]
 [ -5 -15 -20 -15  -5]
 [  3   9  12   9   3]
 [  6  18  24  18   6]]


## 3. **A python function maximum_filter**

In [7]:
from scipy.ndimage import maximum_filter

In [8]:
R = np.array([
  [1, 3, 2, 4],
  [2, 5, 6, 8],
  [7, 1, 1, 3],
  [4, 3, 2, 2]
])
# foorprint is used to determine whether the element should be considered as maximum
footprint = np.ones((3, 3))
B = maximum_filter(input = R, footprint = footprint, mode = 'reflect')
print(B)

[[5 6 8 8]
 [7 7 8 8]
 [7 7 8 8]
 [7 7 3 3]]


## 4. **A python function np.argwhere**

In [15]:
# print the index of non-zero elements
A = np.array([[0,0,0],[1,2,1]])
B = np.argwhere(A)
print(B)

print(np.argwhere(A==0))

[[1 0]
 [1 1]
 [1 2]]
[[0 0]
 [0 1]
 [0 2]]


## 5. **A python function np.argsort**

In [18]:
# return the indices that will sort the array.
A = np.array([[1,2,3],[4,5,-6]])
B = np.argsort(A)
print(B)

[[0 1 2]
 [2 0 1]]


## 6. A python function np.where

In [4]:
A = np.array([[1,2,3],[4,5,-6],[7,8,9]])
indices = np.where(A>0)
print(indices)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))
